export const lightBlue = '#93deff'
export const blue = '#1e90ff'
export const white = '#fff'
export const lightGrey = '#eee'
export const grey = '#757575'
export const pastelYellow = '#fdec96'
export const lightGreen = '#63d863'
